#!/usr/bin/env python3
"""Emit the narrow set of signals an agent cannot cheaply derive by hand.

Stdlib-only. No third-party imports. Read-only against the target path.

This is deliberately *not* a general scanner. Stack, manifests, tree, and env
vars are one cheap command each — the skill reads those directly. This script
computes only what is expensive or impossible to get by hand:

Usage:
    python3 signals.py <path>

Output keys:
    target            resolved absolute path of the scanned repo
    marker            the line-1 comment that marks a skill-owned file
    area_shape        { area: { files, max_depth, has_subpackages,
                                earns_own_file } } — earns_own_file is the
                      SINGLE SOURCE OF TRUTH for the KTD3 numeric thresholds
    co_change         pairs of files that change together in git history
    ripple            { area: [{ from, files }] } — which other areas import
                      from a given area (inbound dependency edges)
    existing_outputs  { marked: [path,...],
                        preexisting_onboarding: [{ path, name, is_symlink,
                                                   symlink_target? },...] }
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

# The line-1 marker that distinguishes a skill-owned file from human-authored
# content. Its text states the Model A contract: the skill rewrites the file on
# re-run and does not preserve hand-edits. Shared by the skill, the reference,
# and the tests — defined here once.
MARKER = "<!-- generated by docs:generate; safe to hand-edit; rerun overwrites -->"

IGNORE_DIRS = {
    ".git", "node_modules", "dist", "build", "out", "target", ".next", ".nuxt",
    ".cache", "vendor", "third_party", "__pycache__", ".venv", "venv",
    ".tox", ".mypy_cache", ".pytest_cache", ".idea", ".vscode",
    "cdk.out", ".ruff_cache", ".terraform", ".gradle", ".dart_tool",
}

# Source suffixes whose import/require lines feed the ripple scan.
CODE_SUFFIXES = {
    ".py", ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx",
    ".go", ".rs", ".rb", ".java", ".kt",
}

# KTD3 numeric thresholds. These live HERE and nowhere else — the plan and
# output-spec.md describe the rule but never restate the numbers, to avoid
# drift. earns_own_file is derived from them; the residual core-code judgement
# is left to the skill.
_AREA_MAX_PREFIX_DEPTH = 4   # how deep to consider candidate areas
_AREA_MIN_FILES = 15
_AREA_MIN_DEPTH = 3          # files inside must reach this many path parts


def _list_tracked(repo: Path) -> list[Path]:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(repo), "ls-files"],
            stderr=subprocess.DEVNULL, text=True,
        )
        tracked = [repo / line for line in out.splitlines() if line]
        if tracked:
            return tracked
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    files: list[Path] = []
    for root, dirs, names in os.walk(repo):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        for n in names:
            files.append(Path(root) / n)
    return files


def _read_text(p: Path, limit: int = 60_000) -> str:
    try:
        with p.open("r", encoding="utf-8", errors="replace") as fh:
            return fh.read(limit)
    except OSError:
        return ""


def _rels(repo: Path, files: list[Path]) -> list[Path]:
    out: list[Path] = []
    for f in files:
        try:
            rel = f.relative_to(repo)
        except ValueError:
            continue
        if any(part in IGNORE_DIRS for part in rel.parts):
            continue
        out.append(rel)
    return out


def _area_shape(rels: list[Path]) -> dict:
    """For every directory at depth 1..N, emit shape + earns_own_file.

    An area earns its own file when it is sizeable and internally structured:
    has_subpackages and max_depth >= _AREA_MIN_DEPTH and files >= _AREA_MIN_FILES.
    Recursive, so a nested mega-area qualifies independently of its parent.
    """
    by_prefix: dict[str, list[Path]] = {}
    for rel in rels:
        for depth in range(1, min(_AREA_MAX_PREFIX_DEPTH, len(rel.parts))):
            prefix = "/".join(rel.parts[:depth])
            by_prefix.setdefault(prefix, []).append(rel)

    out: dict = {}
    for prefix, group in by_prefix.items():
        depth = prefix.count("/") + 1
        max_depth = max(len(r.parts) for r in group)
        # has_subpackages: >=2 distinct immediate child dirs that hold files.
        children = {r.parts[depth] for r in group if len(r.parts) > depth + 1}
        has_subpackages = len(children) >= 2
        files = len(group)
        out[prefix] = {
            "files": files,
            "max_depth": max_depth,
            "has_subpackages": has_subpackages,
            "earns_own_file": (
                has_subpackages
                and max_depth >= _AREA_MIN_DEPTH
                and files >= _AREA_MIN_FILES
            ),
        }
    return out


def _co_change(repo: Path) -> list[dict]:
    """Files that change together in recent git history.

    Surfaces hidden coupling — pairs co-edited often without an explicit import
    link. Caps commits at 300, ignores giant commits (> 12 files). Empty (no
    crash) when the path is not a git repo.
    """
    try:
        out = subprocess.check_output(
            ["git", "-C", str(repo), "log", "-n", "300", "--name-only",
             "--no-merges", "--pretty=format:---COMMIT---"],
            stderr=subprocess.DEVNULL, text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []
    from collections import Counter
    from itertools import combinations
    pairs: Counter = Counter()
    current: list[str] = []

    def flush(group: list[str]) -> None:
        unique = sorted(set(group))
        if 2 <= len(unique) <= 12:
            for a, b in combinations(unique, 2):
                pairs[(a, b)] += 1

    for line in out.splitlines():
        if line.startswith("---COMMIT---"):
            flush(current)
            current = []
        elif line:
            current.append(line)
    flush(current)
    return [
        {"a": a, "b": b, "count": c}
        for (a, b), c in pairs.most_common(15)
        if c >= 3
    ]


def _ripple(repo: Path, rels: list[Path], area_shape: dict) -> dict:
    """Per area, which other areas reference it (inbound dependency edges).

    Computed at the granularity of areas that can earn their own file — every
    top-level dir plus any nested area with earns_own_file — so a nested area
    that earns a CLAUDE.md still gets a "called by" signal. Coarse but cheap:
    matches `from <area>`, `import <area>`, or path-like `<area>/`.
    """
    from collections import Counter

    # Read code-file text once, keyed by relative path.
    corpus: dict[str, str] = {}
    for rel in rels:
        if rel.suffix.lower() not in CODE_SUFFIXES:
            continue
        if len(corpus) >= 3000:
            break
        t = _read_text(repo / rel)
        if t:
            corpus[rel.as_posix()] = t

    # Candidate targets: top-level dirs + nested areas that earn their own file.
    top_level = sorted({r.parts[0] for r in rels if len(r.parts) > 1})
    nested = [a for a, s in area_shape.items() if "/" in a and s["earns_own_file"]]
    targets = sorted(set(top_level) | set(nested))

    def area_of(path: str) -> str:
        # Longest matching target prefix owns the file (so nested areas win).
        owner = path.split("/", 1)[0] if "/" in path else "(root)"
        for t in targets:
            if "/" in t and (path == t or path.startswith(t + "/")):
                if len(t) > len(owner):
                    owner = t
        return owner

    out: dict = {}
    for target in targets:
        last = target.rsplit("/", 1)[-1]
        pat = re.compile(
            rf"(?:from\s+{re.escape(last)}\b|"
            rf"import\s+{re.escape(last)}\b|"
            rf"['\"`]{re.escape(target)}/|"
            rf"/{re.escape(last)}/)"
        )
        callers: Counter = Counter()
        for path, text in corpus.items():
            src = area_of(path)
            if src == target or (path == target or path.startswith(target + "/")):
                continue
            if pat.search(text):
                callers[src] += 1
        if callers:
            out[target] = [
                {"from": k, "files": v} for k, v in callers.most_common(5)
            ]
    return out


_ONBOARDING_NAMES = {"CLAUDE.md", "AGENTS.md"}


def _existing_outputs(repo: Path) -> dict:
    """One authoritative pass over what already exists, for re-run safety.

    - marked: every Markdown file carrying the skill's marker (any name, any
      depth) — these are skill-owned and reconciled/regenerated in place (R8a).
    - preexisting_onboarding: by FILENAME only, any UNMARKED CLAUDE.md and any
      AGENTS.md at root or in subdirectories — deliberate prior work the skill
      must ask about rather than shadow (R8b). No content sniffing.

    Walks the filesystem rather than the git index: a just-generated or
    gitignored area CLAUDE.md / deep-dive doc must still be seen so re-run
    reconciliation and orphan detection are complete. Only `.md` files are
    read (the skill never emits anything else), bounding the cost.
    """
    marked: list[str] = []
    onboarding: list[dict] = []
    seen: set[str] = set()

    def consider(p: Path, relposix: str) -> None:
        if relposix in seen:
            return
        if not (p.exists() or p.is_symlink()):
            return
        seen.add(relposix)
        head = _read_text(p, limit=2048)
        if MARKER in head:
            marked.append(relposix)
        elif p.name in _ONBOARDING_NAMES:
            entry: dict = {
                "path": relposix,
                "name": p.name,
                "is_symlink": p.is_symlink(),
            }
            if p.is_symlink():
                try:
                    entry["symlink_target"] = os.readlink(p)
                except OSError:
                    entry["symlink_target"] = None
            onboarding.append(entry)

    for root, dirs, names in os.walk(repo):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        for n in names:
            if not (n.endswith(".md") or n in _ONBOARDING_NAMES):
                continue
            p = Path(root) / n
            consider(p, p.relative_to(repo).as_posix())

    # Symlinked onboarding (e.g. AGENTS.md -> .claude/CLAUDE.md) may not surface
    # as a regular file in the walk; probe well-known paths explicitly.
    for extra in (".claude/CLAUDE.md", ".claude/AGENTS.md"):
        consider(repo / extra, extra)

    return {
        "marked": sorted(marked),
        "preexisting_onboarding": sorted(onboarding, key=lambda e: e["path"]),
    }


def main(argv: list[str]) -> int:
    if len(argv) < 1:
        print("usage: signals.py <path>", file=sys.stderr)
        return 2
    repo = Path(argv[0]).resolve()
    if not repo.is_dir():
        print(f"error: not a directory: {repo}", file=sys.stderr)
        return 2

    files = _list_tracked(repo)
    rels = _rels(repo, files)
    area_shape = _area_shape(rels)
    payload = {
        "target": str(repo),
        "marker": MARKER,
        "area_shape": area_shape,
        "co_change": _co_change(repo),
        "ripple": _ripple(repo, rels, area_shape),
        "existing_outputs": _existing_outputs(repo),
    }
    json.dump(payload, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
